services:
  minecraft:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      
      # Server properties
      INIT_MEMORY: 1G
      MAX_MEMORY: 6G
      SERVER_NAME: Cursed Walking Server
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: world-%date:yyyy-MM-dd%
      DIFFICULTY: hard
      OPS: |
        Zhrssh

      # CurseForge Config
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: cursed-walking-a-modern-zombie-apocalypse

    volumes:
      - ./data:/data
